# Generates deploy/demo-fol/sql/001-fol-standard-clauses.sql from LMA-style clause catalogue.
# Target: executive demo FOL with 100+ rendered pages when combined with rich bindings.
# Run: .\deploy\demo-fol\generate-clauses-sql.ps1

$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$OutFile = Join-Path $Root 'sql/001-fol-standard-clauses.sql'
$Library = Join-Path $Root 'lma-clause-library.ps1'
$Null = New-Item -ItemType Directory -Force -Path (Split-Path $OutFile)

if (-not (Test-Path $Library)) { throw "Missing clause library: $Library" }
. $Library
. (Join-Path $Root 'fol-catalog-shared.ps1')

function Escape-Sql([string]$Value) {
    return $Value.Replace("'", "''")
}

function Escape-Json([string]$Value) {
    return $Value.Replace('\', '\\').Replace('"', '\"').Replace("`n", '\n').Replace("`r", '')
}

function Clause-Json([string[]]$Paragraphs) {
    $blocks = $Paragraphs | ForEach-Object { "{`"type`":`"paragraph`",`"text`":`"$(Escape-Json $_)`"}" }
    return "{`"blocks`":[$($blocks -join ',')]}"
}

function Resolve-ClauseParagraphs([hashtable]$Entry) {
    if ($Entry.ContainsKey('Builder')) {
        return & $Entry.Builder
    }
    if ($Entry.ContainsKey('Schedule')) {
        $extra = @()
        if ($Entry.ContainsKey('Extra')) { $extra = @($Entry.Extra) }
        return Build-ScheduleParagraphs -ScheduleNumber $Entry.Schedule -Title $Entry.Name -ExtraParagraphs $extra
    }
    $clauseNumber = ($Entry.Name -split '\.')[0].Trim()
    return Build-LmaSectionParagraphs -ClauseNumber $clauseNumber -Title (($Entry.Name -split '\.', 2)[1].Trim()) -SubClauseTopics @($Entry.Topics)
}

$Clauses = [System.Collections.Generic.List[object]]::new()
foreach ($Entry in Get-LmaSectionCatalog) {
    $Paragraphs = Resolve-ClauseParagraphs $Entry
    $Clauses.Add([ordered]@{
        Code = $Entry.Code
        Name = $Entry.Name
        Paragraphs = $Paragraphs
    })
}

$Lines = New-Object System.Collections.Generic.List[string]
$Lines.Add('-- Generated by deploy/demo-fol/generate-clauses-sql.ps1')
$Lines.Add('-- Meridian Global Banking Corporation — LMA-style wholesale FOL clauses (CORP group, 100+ page demo target)')
$Lines.Add('BEGIN;')
$Lines.Add('')

$Index = 1
foreach ($Clause in ($Clauses | Sort-Object { $_.Code })) {
    $ModuleId = ('aaaaaaaa-aaaa-aaaa-aaaa-{0:D12}' -f $Index)
    $VersionId = ('bbbbbbbb-bbbb-bbbb-bbbb-{0:D12}' -f $Index)
    $Json = Clause-Json $Clause.Paragraphs
    $anchorId = Resolve-FolHybridAnchorId ([hashtable]@{ Name = $Clause.Name })
    $Lines.Add("-- $($Clause.Code) -> $anchorId ($(@($Clause.Paragraphs).Count) paragraphs)")
    $Lines.Add(@"
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT '$ModuleId', '$(Escape-Sql $Clause.Code)', 'CORP', '$(Escape-Sql $Clause.Name)', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = '$(Escape-Sql $Clause.Code)' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT '$VersionId', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '$(Escape-Sql $Json)',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = '$(Escape-Sql $Clause.Code)' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

UPDATE content_module_version v
SET content_structure_json = '$(Escape-Sql $Json)',
    change_description = 'Executive demo refresh — LMA-style expanded clauses',
    updated_at = (NOW() AT TIME ZONE 'UTC'),
    updated_by = '10000007'
FROM content_module cm
WHERE v.module_id = cm.id
  AND cm.module_code = '$(Escape-Sql $Clause.Code)'
  AND cm.deleted_at IS NULL
  AND v.semantic_version = '1.0.0';
"@)
    $Lines.Add('')
    $Index++
}

$Lines.Add('COMMIT;')
Set-Content -Path $OutFile -Value ($Lines -join [Environment]::NewLine) -Encoding UTF8
$totalParagraphs = ($Clauses | ForEach-Object { @($_.Paragraphs).Count } | Measure-Object -Sum).Sum
Write-Host "Wrote $($Clauses.Count) clauses ($totalParagraphs paragraphs) -> $OutFile"
