/** Spread helpers for assembleTemplateDetailControllerApi — keeps public surface identical. */

export function assembleTemplateDetailJourneySlice(navigation: {
  showAuthorJourney: unknown
  authorJourneyContext: unknown
  showTesterJourney: unknown
  testerJourneyContext: unknown
  showApproverJourney: unknown
  approverJourneyContext: unknown
  showTeamLeadJourney: unknown
  teamLeadJourneyContext: unknown
  handleJourneyCreate: unknown
  handleJourneyDesign: unknown
  handleJourneyTrialGenerate: unknown
  handleJourneySubmitForTest: unknown
  handleJourneySubmitForApproval: unknown
  handleJourneyReviewRequest: unknown
  handleJourneyCheckEvidence: unknown
  handleJourneyRecordResult: unknown
  handleJourneyApproverReviewRequest: unknown
  handleJourneyApproverReviewSubmission: unknown
  handleJourneyApproverRecordDecision: unknown
  handleJourneyTeamLeadReviewGoLiveRequest: unknown
  handleJourneyTeamLeadRunPreReleaseChecks: unknown
  handleJourneyTeamLeadConfirmGoLive: unknown
  testerEvidenceViewed: unknown
  approverEvidenceViewed: unknown
  loadFailed: unknown
  activeDetailTab: unknown
  activeDevWorkspaceTab: unknown
  detailTabs: unknown
  loadTemplate: unknown
  backToList: unknown
  openLifecyclePanel: unknown
  openDevWorkspaceTab: unknown
}) {
  return {
    loadFailed: navigation.loadFailed,
    activeDetailTab: navigation.activeDetailTab,
    activeDevWorkspaceTab: navigation.activeDevWorkspaceTab,
    detailTabs: navigation.detailTabs,
    showAuthorJourney: navigation.showAuthorJourney,
    authorJourneyContext: navigation.authorJourneyContext,
    showTesterJourney: navigation.showTesterJourney,
    testerJourneyContext: navigation.testerJourneyContext,
    showApproverJourney: navigation.showApproverJourney,
    approverJourneyContext: navigation.approverJourneyContext,
    showTeamLeadJourney: navigation.showTeamLeadJourney,
    teamLeadJourneyContext: navigation.teamLeadJourneyContext,
    handleJourneyCreate: navigation.handleJourneyCreate,
    handleJourneyDesign: navigation.handleJourneyDesign,
    handleJourneyTrialGenerate: navigation.handleJourneyTrialGenerate,
    handleJourneySubmitForTest: navigation.handleJourneySubmitForTest,
    handleJourneySubmitForApproval: navigation.handleJourneySubmitForApproval,
    handleJourneyReviewRequest: navigation.handleJourneyReviewRequest,
    handleJourneyCheckEvidence: navigation.handleJourneyCheckEvidence,
    handleJourneyRecordResult: navigation.handleJourneyRecordResult,
    handleJourneyApproverReviewRequest: navigation.handleJourneyApproverReviewRequest,
    handleJourneyApproverReviewSubmission: navigation.handleJourneyApproverReviewSubmission,
    handleJourneyApproverRecordDecision: navigation.handleJourneyApproverRecordDecision,
    handleJourneyTeamLeadReviewGoLiveRequest: navigation.handleJourneyTeamLeadReviewGoLiveRequest,
    handleJourneyTeamLeadRunPreReleaseChecks: navigation.handleJourneyTeamLeadRunPreReleaseChecks,
    handleJourneyTeamLeadConfirmGoLive: navigation.handleJourneyTeamLeadConfirmGoLive,
    testerEvidenceViewed: navigation.testerEvidenceViewed,
    approverEvidenceViewed: navigation.approverEvidenceViewed,
    loadTemplate: navigation.loadTemplate,
    backToList: navigation.backToList,
    openLifecyclePanel: navigation.openLifecyclePanel,
    openDevWorkspaceTab: navigation.openDevWorkspaceTab,
  }
}

export function assembleTemplateDetailLifecycleSlice(lifecycle: {
  authorJourneyPrimaryCtaDisabled: unknown
  showLifecycleSection: unknown
  showGovernanceSection: unknown
  showDraftActions: unknown
  showTestingDecisionActions: unknown
  showSubmitForApproval: unknown
  showApprovalDecisionActions: unknown
  showPublishActions: unknown
  showStopAction: unknown
  showRestoreAction: unknown
  showDeprecateAction: unknown
  showDeleteTemplateAction: unknown
  publishGateItems: unknown
  publishGateReady: unknown
  publishVersion: unknown
  publishBumpLevel: unknown
  publishBumpOptions: unknown
  publishVersionConflict: unknown
  loadingPublishGate: unknown
  publishGateLoadError: unknown
  publishCoverageSummary: unknown
  publishChangeDiffSummary: unknown
  submitGateItems: unknown
  submitGateReady: unknown
  loadingSubmitGate: unknown
  submitGateLoadError: unknown
  submitCoverageSummary: unknown
  submitChangeDiffSummary: unknown
  bindingGateResult: unknown
  lifecycleComment: unknown
  lifecycleCommentDialogOpen: unknown
  decisionDialogOpen: unknown
  decisionDialogMode: unknown
  publishSummaryOpen: unknown
  submitSummaryOpen: unknown
  submitForTestDialogOpen: unknown
  loadPublishGateData: unknown
  loadSubmitGateData: unknown
  handleSubmitForTest: unknown
  handleTestDecision: unknown
  openApprovalRejectDialog: unknown
  submitLifecycleDecision: unknown
  handleSubmitForApproval: unknown
  confirmSubmitFromSummary: unknown
  handleApprovalDecision: unknown
  handlePublish: unknown
  confirmPublishFromSummary: unknown
  handleGovernanceAction: unknown
  handleDeleteTemplate: unknown
}) {
  return {
    authorJourneyPrimaryCtaDisabled: lifecycle.authorJourneyPrimaryCtaDisabled,
    showLifecycleSection: lifecycle.showLifecycleSection,
    showGovernanceSection: lifecycle.showGovernanceSection,
    showDraftActions: lifecycle.showDraftActions,
    showTestingDecisionActions: lifecycle.showTestingDecisionActions,
    showSubmitForApproval: lifecycle.showSubmitForApproval,
    showApprovalDecisionActions: lifecycle.showApprovalDecisionActions,
    showPublishActions: lifecycle.showPublishActions,
    showStopAction: lifecycle.showStopAction,
    showRestoreAction: lifecycle.showRestoreAction,
    showDeprecateAction: lifecycle.showDeprecateAction,
    showDeleteTemplateAction: lifecycle.showDeleteTemplateAction,
    publishGateItems: lifecycle.publishGateItems,
    publishGateReady: lifecycle.publishGateReady,
    publishVersion: lifecycle.publishVersion,
    publishBumpLevel: lifecycle.publishBumpLevel,
    publishBumpOptions: lifecycle.publishBumpOptions,
    publishVersionConflict: lifecycle.publishVersionConflict,
    loadingPublishGate: lifecycle.loadingPublishGate,
    publishGateLoadError: lifecycle.publishGateLoadError,
    publishCoverageSummary: lifecycle.publishCoverageSummary,
    publishChangeDiffSummary: lifecycle.publishChangeDiffSummary,
    submitGateItems: lifecycle.submitGateItems,
    submitGateReady: lifecycle.submitGateReady,
    loadingSubmitGate: lifecycle.loadingSubmitGate,
    submitGateLoadError: lifecycle.submitGateLoadError,
    submitCoverageSummary: lifecycle.submitCoverageSummary,
    submitChangeDiffSummary: lifecycle.submitChangeDiffSummary,
    bindingGateResult: lifecycle.bindingGateResult,
    lifecycleComment: lifecycle.lifecycleComment,
    lifecycleCommentDialogOpen: lifecycle.lifecycleCommentDialogOpen,
    decisionDialogOpen: lifecycle.decisionDialogOpen,
    decisionDialogMode: lifecycle.decisionDialogMode,
    publishSummaryOpen: lifecycle.publishSummaryOpen,
    submitSummaryOpen: lifecycle.submitSummaryOpen,
    submitForTestDialogOpen: lifecycle.submitForTestDialogOpen,
    loadPublishGateData: lifecycle.loadPublishGateData,
    loadSubmitGateData: lifecycle.loadSubmitGateData,
    handleSubmitForTest: lifecycle.handleSubmitForTest,
    handleTestDecision: lifecycle.handleTestDecision,
    openApprovalRejectDialog: lifecycle.openApprovalRejectDialog,
    submitLifecycleDecision: lifecycle.submitLifecycleDecision,
    handleSubmitForApproval: lifecycle.handleSubmitForApproval,
    confirmSubmitFromSummary: lifecycle.confirmSubmitFromSummary,
    handleApprovalDecision: lifecycle.handleApprovalDecision,
    handlePublish: lifecycle.handlePublish,
    confirmPublishFromSummary: lifecycle.confirmPublishFromSummary,
    handleGovernanceAction: lifecycle.handleGovernanceAction,
    handleDeleteTemplate: lifecycle.handleDeleteTemplate,
  }
}
