-- Generated by deploy/demo-fol/generate-clauses-sql.ps1
-- Meridian Global Banking Corporation 鈥?wholesale FOL standard clauses (CORP group)
BEGIN;

-- MOD-FOL-SCH-01 -> FOL_SCH_01
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000001', 'MOD-FOL-SCH-01', 'CORP', 'Schedule 1 鈥?Facility Particulars', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SCH-01' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000001', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"Schedule 1 鈥?Facility Particulars forms an integral part of the Facility Offer Letter and shall be completed with facility-specific commercial terms prior to signing."},{"type":"paragraph","text":"Tables, defined terms, and annexed forms in this schedule typically account for a substantial portion of the overall page count in a signed documentation set."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SCH-01' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SCH-02 -> FOL_SCH_02
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000002', 'MOD-FOL-SCH-02', 'CORP', 'Schedule 2 鈥?Conditions Precedent', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SCH-02' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000002', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"Schedule 2 鈥?Conditions Precedent forms an integral part of the Facility Offer Letter and shall be completed with facility-specific commercial terms prior to signing."},{"type":"paragraph","text":"Tables, defined terms, and annexed forms in this schedule typically account for a substantial portion of the overall page count in a signed documentation set."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SCH-02' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SCH-03 -> FOL_SCH_03
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000003', 'MOD-FOL-SCH-03', 'CORP', 'Schedule 3 鈥?Representations', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SCH-03' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000003', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"Schedule 3 鈥?Representations forms an integral part of the Facility Offer Letter and shall be completed with facility-specific commercial terms prior to signing."},{"type":"paragraph","text":"Tables, defined terms, and annexed forms in this schedule typically account for a substantial portion of the overall page count in a signed documentation set."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SCH-03' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SCH-04 -> FOL_SCH_04
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000004', 'MOD-FOL-SCH-04', 'CORP', 'Schedule 4 鈥?Form of Utilisation Request', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SCH-04' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000004', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"Schedule 4 鈥?Form of Utilisation Request forms an integral part of the Facility Offer Letter and shall be completed with facility-specific commercial terms prior to signing."},{"type":"paragraph","text":"Tables, defined terms, and annexed forms in this schedule typically account for a substantial portion of the overall page count in a signed documentation set."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SCH-04' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SCH-05 -> FOL_SCH_05
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000005', 'MOD-FOL-SCH-05', 'CORP', 'Schedule 5 鈥?Fees', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SCH-05' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000005', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"Schedule 5 鈥?Fees forms an integral part of the Facility Offer Letter and shall be completed with facility-specific commercial terms prior to signing."},{"type":"paragraph","text":"Tables, defined terms, and annexed forms in this schedule typically account for a substantial portion of the overall page count in a signed documentation set."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SCH-05' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SCH-06 -> FOL_SCH_06
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000006', 'MOD-FOL-SCH-06', 'CORP', 'Schedule 6 鈥?Security Principles', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SCH-06' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000006', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"Schedule 6 鈥?Security Principles forms an integral part of the Facility Offer Letter and shall be completed with facility-specific commercial terms prior to signing."},{"type":"paragraph","text":"Tables, defined terms, and annexed forms in this schedule typically account for a substantial portion of the overall page count in a signed documentation set."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SCH-06' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-01 -> FOL_SEC_01
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000007', 'MOD-FOL-SEC-01', 'CORP', '1. Definitions and Interpretation', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-01' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000007', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"In this Facility Offer Letter and the Finance Documents, unless the context otherwise requires, capitalised terms have the meanings given in Schedule 1 (Definitions) or, if not defined therein, the meanings given in the LMA Single Currency Term Facility Agreement (as published by the Loan Market Association)."},{"type":"paragraph","text":"References to a \"Finance Document\" include this letter, the Fee Letter, the Utilisation Request, any Security Document, and any other document designated as such by the Agent and the Borrower. Clause headings are for convenience only and do not affect interpretation."},{"type":"paragraph","text":"The interpretation principles in Clause 1.2 (Construction) of the Recommended Form apply as if set out in full herein, including rules on inclusive meaning of \"assets\", time of day references to London time, and the meaning of \"know your customer\" or similar checks under applicable law."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-01' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-02 -> FOL_SEC_02
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000008', 'MOD-FOL-SEC-02', 'CORP', '2. The Facility', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-02' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000008', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"Subject to the terms of the Finance Documents, the Lenders agree to make available to the Borrower a multicurrency term loan facility in an aggregate amount equal to the Total Commitments, as set out in the Facility Particulars in Schedule 1."},{"type":"paragraph","text":"The Facility is made available for the Purpose and on the terms that each Lender''s Commitment shall be several and not joint. No Lender shall be obliged to fund more than its Commitment except as provided following an assignment or transfer in accordance with Clause 23 (Changes to the Lenders)."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-02' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-03 -> FOL_SEC_03
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000009', 'MOD-FOL-SEC-03', 'CORP', '3. Purpose', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-03' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000009', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"The Borrower shall apply all amounts borrowed under the Facility towards: (a) refinancing existing external indebtedness of the Group maturing within twelve months of the Signing Date; (b) capital expenditure approved by the board of the Borrower; and (c) general corporate and working capital purposes of the Group."},{"type":"paragraph","text":"No part of the Facility may be applied directly or indirectly towards the acquisition of equity in any entity if such acquisition would result in a Change of Control, or towards any purpose that would cause a violation of applicable sanctions, anti-bribery, or anti-money laundering laws."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-03' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-04 -> FOL_SEC_04
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000010', 'MOD-FOL-SEC-04', 'CORP', '4. Conditions of Utilisation', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-04' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000010', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"4. Conditions of Utilisation 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-04' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-05 -> FOL_SEC_05
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000011', 'MOD-FOL-SEC-05', 'CORP', '5. Utilisation', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-05' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000011', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"5. Utilisation 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-05' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-06 -> FOL_SEC_06
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000012', 'MOD-FOL-SEC-06', 'CORP', '6. Repayment', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-06' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000012', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"6. Repayment 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-06' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-07 -> FOL_SEC_07
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000013', 'MOD-FOL-SEC-07', 'CORP', '7. Prepayment and Cancellation', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-07' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000013', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"7. Prepayment and Cancellation 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-07' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-08 -> FOL_SEC_08
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000014', 'MOD-FOL-SEC-08', 'CORP', '8. Interest', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-08' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000014', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"The rate of interest on each Loan for each Interest Period is the percentage rate per annum which is the aggregate of the applicable Reference Rate and the Margin."},{"type":"paragraph","text":"If the Borrower fails to pay any amount payable by it under a Finance Document on its due date, interest shall accrue on the overdue amount at a rate per annum which is the sum of the rate applicable to the relevant Loan plus 2.00 per cent. per annum, from the due date to the date of actual payment (both before and after judgment)."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-08' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-09 -> FOL_SEC_09
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000015', 'MOD-FOL-SEC-09', 'CORP', '9. Interest Periods', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-09' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000015', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"9. Interest Periods 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-09' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-10 -> FOL_SEC_10
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000016', 'MOD-FOL-SEC-10', 'CORP', '10. Changes to the Calculation of Interest', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-10' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000016', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"10. Changes to the Calculation of Interest 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-10' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-11 -> FOL_SEC_11
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000017', 'MOD-FOL-SEC-11', 'CORP', '11. Fees', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-11' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000017', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"11. Fees 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-11' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-12 -> FOL_SEC_12
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000018', 'MOD-FOL-SEC-12', 'CORP', '12. Tax Gross-Up and Indemnities', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-12' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000018', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"12. Tax Gross-Up and Indemnities 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-12' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-13 -> FOL_SEC_13
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000019', 'MOD-FOL-SEC-13', 'CORP', '13. Increased Costs', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-13' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000019', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"13. Increased Costs 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-13' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-14 -> FOL_SEC_14
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000020', 'MOD-FOL-SEC-14', 'CORP', '14. Other Indemnities', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-14' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000020', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"14. Other Indemnities 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-14' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-15 -> FOL_SEC_15
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000021', 'MOD-FOL-SEC-15', 'CORP', '15. Mitigation by the Lenders', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-15' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000021', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"15. Mitigation by the Lenders 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-15' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-16 -> FOL_SEC_16
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000022', 'MOD-FOL-SEC-16', 'CORP', '16. Costs and Expenses', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-16' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000022', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"16. Costs and Expenses 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-16' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-17 -> FOL_SEC_17
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000023', 'MOD-FOL-SEC-17', 'CORP', '17. Guarantee and Indemnity', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-17' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000023', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"17. Guarantee and Indemnity 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-17' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-18 -> FOL_SEC_18
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000024', 'MOD-FOL-SEC-18', 'CORP', '18. Representations', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-18' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000024', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"18. Representations 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-18' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-19 -> FOL_SEC_19
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000025', 'MOD-FOL-SEC-19', 'CORP', '19. Information Undertakings', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-19' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000025', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"19. Information Undertakings 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-19' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-20 -> FOL_SEC_20
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000026', 'MOD-FOL-SEC-20', 'CORP', '20. Financial Covenants', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-20' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000026', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"The Borrower shall ensure that, tested quarterly on each Quarterly Financial Statement Date on a rolling twelve-month basis: (a) the Consolidated Net Leverage Ratio shall not exceed 3.50:1.00; and (b) the Consolidated Interest Cover Ratio shall not be less than 3.00:1.00."},{"type":"paragraph","text":"The Borrower shall also maintain Minimum Liquidity of not less than USD 10,000,000 (or equivalent in other currencies) at all times, measured as unrestricted cash and cash equivalents held in accounts with Acceptable Banks."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-20' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-21 -> FOL_SEC_21
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000027', 'MOD-FOL-SEC-21', 'CORP', '21. General Undertakings', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-21' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000027', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"21. General Undertakings 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-21' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-22 -> FOL_SEC_22
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000028', 'MOD-FOL-SEC-22', 'CORP', '22. Events of Default', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-22' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000028', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"Each of the events set out in this Clause 22 constitutes an Event of Default, including: non-payment of any amount due under a Finance Document (subject to three Business Days'' grace for administrative error); breach of financial covenant not remedied within any applicable cure period; material misrepresentation; cross-default in respect of Financial Indebtedness exceeding USD 5,000,000 (or equivalent); insolvency events; unlawfulness; and cessation of business."},{"type":"paragraph","text":"Upon the occurrence of an Event of Default which is continuing, the Agent may, and shall if so directed by the Majority Lenders, by notice to the Borrower cancel the Total Commitments and/or declare all or part of the outstanding Loans, together with accrued interest and all other amounts accrued or outstanding under the Finance Documents, immediately due and payable."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-22' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-23 -> FOL_SEC_23
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000029', 'MOD-FOL-SEC-23', 'CORP', '23. Changes to the Lenders', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-23' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000029', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"23. Changes to the Lenders 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-23' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-24 -> FOL_SEC_24
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000030', 'MOD-FOL-SEC-24', 'CORP', '24. The Agent and the Arrangers', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-24' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000030', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"24. The Agent and the Arrangers 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-24' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-25 -> FOL_SEC_25
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000031', 'MOD-FOL-SEC-25', 'CORP', '25. Conduct of Business by the Finance Parties', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-25' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000031', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"25. Conduct of Business by the Finance Parties 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-25' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-26 -> FOL_SEC_26
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000032', 'MOD-FOL-SEC-26', 'CORP', '26. Sharing among the Finance Parties', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-26' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000032', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"26. Sharing among the Finance Parties 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-26' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-27 -> FOL_SEC_27
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000033', 'MOD-FOL-SEC-27', 'CORP', '27. Payment Mechanics', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-27' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000033', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"27. Payment Mechanics 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-27' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-28 -> FOL_SEC_28
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000034', 'MOD-FOL-SEC-28', 'CORP', '28. Set-Off', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-28' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000034', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"28. Set-Off 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-28' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-29 -> FOL_SEC_29
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000035', 'MOD-FOL-SEC-29', 'CORP', '29. Notices', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-29' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000035', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"29. Notices 鈥?standard wholesale-bank language as agreed with counsel and aligned to the LMA recommended form for term facilities."},{"type":"paragraph","text":"This demonstration clause is approved for management preview. Production packs replace this body with facility-specific negotiated text, defined terms cross-references, and worked examples spanning multiple pages."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-29' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

-- MOD-FOL-SEC-30 -> FOL_SEC_30
INSERT INTO content_module (id, module_code, group_code, name, description, shared_group_codes_json, created_by, updated_by)
SELECT 'aaaaaaaa-aaaa-aaaa-aaaa-000000000036', 'MOD-FOL-SEC-30', 'CORP', '30. Governing Law and Jurisdiction', 'Wholesale FOL standard clause (executive demo)', '[]', '10000003', '10000003'
WHERE NOT EXISTS (
    SELECT 1 FROM content_module WHERE module_code = 'MOD-FOL-SEC-30' AND deleted_at IS NULL
);

INSERT INTO content_module_version (
    id, module_id, semantic_version, review_state, lifecycle_state,
    content_structure_json, change_description, created_by, updated_by
)
SELECT 'bbbbbbbb-bbbb-bbbb-bbbb-000000000036', cm.id, '1.0.0', 'APPROVED', 'ACTIVE',
       '{"blocks":[{"type":"paragraph","text":"This Agreement and any non-contractual obligations arising out of or in connection with it are governed by English law."},{"type":"paragraph","text":"The courts of England have exclusive jurisdiction to settle any dispute arising out of or in connection with this Agreement (including a dispute regarding the existence, validity, or termination of this Agreement). The parties irrevocably submit to the jurisdiction of the English courts."}]}',
       'Executive demo import', '10000003', '10000007'
FROM content_module cm
WHERE cm.module_code = 'MOD-FOL-SEC-30' AND cm.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM content_module_version v
      WHERE v.module_id = cm.id AND v.semantic_version = '1.0.0'
  );

COMMIT;
