import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import type { TableColumnFilterOption } from '@/composables/useTableFilterOptions'
import { auditEventTypeMessageKey } from '@/utils/auditEventLabels'

/** Known audit event types with i18n labels under `audit.eventTypes.*`. */
export const AUDIT_EVENT_TYPE_CODES = [
  'PUBLISH',
  'RECORD_APPROVAL_DECISION',
  'SUBMIT_FOR_APPROVAL',
  'RECORD_TEST_DECISION',
  'SUBMIT_FOR_TEST',
  'API_POLICY_UPDATED',
  'API_CREDENTIAL_CREATED',
  'API_CREDENTIAL_ROTATED',
  'API_CREDENTIAL_REVOKED',
  'USER_CREATED',
  'USER_UPDATED',
  'USER_DISABLED',
  'USER_ENABLED',
  'USER_PASSWORD_RESET',
  'USER_DELETED',
  'GROUP_CREATED',
  'GROUP_UPDATED',
  'GROUP_DISABLED',
  'GROUP_ENABLED',
  'IDENTITY_ESCALATION_DENIED',
  'RISK_PROMPT_CONFIG_UPDATED',
  'COLLABORATION_TIMEOUT_CONFIG_UPDATED',
  'COLLABORATION_TIMEOUT_ESCALATION',
  'COLLABORATION_WORK_ITEM_CREATED',
  'COLLABORATION_WORK_ITEM_RESOLVED',
  'CONTENT_MODULE_CREATED',
  'CONTENT_MODULE_VERSION_CREATED',
  'CONTENT_MODULE_VERSION_UPDATED',
  'CONTENT_MODULE_SHARED_GROUP_CODES_UPDATED',
  'CONTENT_MODULE_REVIEW_TRANSITION',
  'CONTENT_MODULE_LIFECYCLE_OPERATION',
  'CONTENT_MODULE_BULK_REPIN',
  'TEMPLATE_EXPORTED',
  'TEMPLATE_IMPORTED',
  'TEMPLATE_IMPORT_DRY_RUN',
  'TEMPLATE_TEST_DATA_PII_EXPLICIT_CONFIRM',
  'INVOCATION_REGENERATED',
  'ASSET_LIBRARY_UPLOAD',
  'ASSET_LIBRARY_DISABLE',
  'ASSET_LIBRARY_REUPLOAD',
  'ASSET_LIBRARY_MIGRATE_QUARANTINE',
  'LIBRARY_EXPORT',
  'LEGAL_HOLD_CREATED',
  'LEGAL_HOLD_RELEASED',
  'TEMPLATE_ANNUAL_REVIEW_COMPLETED',
  'DOCUMENT_BRAND_CREATED',
  'DOCUMENT_BRAND_UPDATED',
  'LEGAL_ENTITY_CREATED',
  'LEGAL_ENTITY_UPDATED',
  'GROUP_DEFAULT_LEGAL_ENTITY_UPDATED',
] as const

export function useAuditEventTypeOptions() {
  const { t, te } = useI18n()

  return computed<TableColumnFilterOption[]>(() =>
    AUDIT_EVENT_TYPE_CODES.map((eventType) => {
      const key = auditEventTypeMessageKey(eventType)
      return {
        value: eventType,
        label: te(key) ? t(key) : eventType,
      }
    }),
  )
}
