package com.bank.docgen.rendering.domain;

public enum FidelityWarningCode {
    CONTROLLED_STYLE_FALLBACK,
    LOW_RISK_PAGINATION_DIFFERENCE,
    PARTIAL_TABLE_LAYOUT_ADJUSTMENT,
    UNRESOLVED_VARIABLE,
    MISSING_ANCHOR_CONTENT,
    UNSUPPORTED_NODE,
    IMAGE_SCALING_ADJUSTED,
    MISSING_STYLE_REFERENCE,
    INAPPLICABLE_STYLE,
    DIRECT_FORMAT_OUT_OF_WHITELIST,
    DIRECT_FORMAT_GLOBAL_LAYOUT,
    NESTED_TABLE,
    UNRELIABLE_TABLE_LAYOUT,
    INVALID_TABLE_COMPONENT,
    SEAL_OUTSIDE_AUTHORIZED_AREA,
    SEAL_SCALING_NOT_ALLOWED,
    MISSING_REFERENCE_KEY,
    DUPLICATE_NUMBER,
    BROKEN_NUMBER_CROSS_REFERENCE
}
