package com.bank.docgen.template.domain;

public enum PublishGateCheckCode {
    ANCHOR_INTEGRITY,
    VARIABLE_SCHEMA,
    RULE_BOUNDS,
    TEST_RESULTS,
    PREVIEW_PRESENT,
    CHANGE_DIFF,
    APPROVAL_SUMMARY,
    COVERAGE_THRESHOLDS,
    API_POLICY,
    CONTENT_MODULE_REFERENCES,
    CONTENT_MODULE_EFFECTIVE_EXPIRED,
    UNSUPPORTED_STRUCTURED_NODES,
    PASTE_CLEANING_BLOCKERS,
    /** ADR-0042: |pdfPages - authorWordPageCount| exceeds 2× pagination delta budget. */
    PAGINATION_DELTA_BUDGET,
    BLOCKER_STATUS,
    FIDELITY_WARNINGS_VIEWED
}
