spring:
  config:
    activate:
      on-profile: prod

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: when_authorized
    prometheus:
      enabled: true

logging:
  level:
    root: INFO
    com.bank.docgen: INFO
