<script setup lang="ts">
/* eslint-disable vue/no-mutating-props -- c is a reactive controller bag owned by the parent shell */
import TemplateDetailDevWorkspace from '@/views/templates/detail/TemplateDetailDevWorkspace.vue'
import TemplateDetailJourneyStack from '@/views/templates/detail/TemplateDetailJourneyStack.vue'
import TemplateDetailLegacyWorkspace from '@/views/templates/detail/TemplateDetailLegacyWorkspace.vue'
import TemplateDetailDialogs from '@/views/templates/detail/TemplateDetailDialogs.vue'

/** Parent passes reactive(useTemplateDetailController(...)); refs are auto-unwrapped. */
defineProps<{
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  c: any
}>()
</script>

<template>
  <TemplateDetailJourneyStack
    v-if="!c.isDevEditor"
    :template="c.template"
    :template-id="c.templateId"
    :show-author-journey="c.showAuthorJourney"
    :author-journey-context="c.authorJourneyContext"
    :author-templates="c.authorTemplates"
    :author-journey-primary-cta-disabled="c.authorJourneyPrimaryCtaDisabled"
    :show-tester-journey="c.showTesterJourney"
    :tester-journey-context="c.testerJourneyContext"
    :decide-tests="c.decideTests"
    :show-approver-journey="c.showApproverJourney"
    :approver-journey-context="c.approverJourneyContext"
    :decide-approvals="c.decideApprovals"
    :show-team-lead-journey="c.showTeamLeadJourney"
    :team-lead-journey-context="c.teamLeadJourneyContext"
    :publish-templates="c.publishTemplates"
    @create="c.handleJourneyCreate"
    @design="c.handleJourneyDesign"
    @trial-generate="c.handleJourneyTrialGenerate"
    @submit-for-test="c.handleJourneySubmitForTest"
    @submit-for-approval="c.handleJourneySubmitForApproval"
    @review-request="c.handleJourneyReviewRequest"
    @check-evidence="c.handleJourneyCheckEvidence"
    @record-result="c.handleJourneyRecordResult"
    @review-approver-request="c.handleJourneyApproverReviewRequest"
    @review-submission="c.handleJourneyApproverReviewSubmission"
    @record-decision="c.handleJourneyApproverRecordDecision"
    @review-go-live-request="c.handleJourneyTeamLeadReviewGoLiveRequest"
    @run-pre-release-checks="c.handleJourneyTeamLeadRunPreReleaseChecks"
    @confirm-go-live="c.handleJourneyTeamLeadConfirmGoLive"
    @open-lifecycle="c.openLifecyclePanel"
  />

  <TemplateDetailDevWorkspace
    v-if="c.isDevEditor && c.showAuthoringSection"
    :template-id="c.templateId"
    :master-id="c.template.masterId"
    :variables="c.template.variables"
    :bindings="c.template.bindings"
    :rules="c.template.rules"
    :group-code="c.template.groupCode"
    :lifecycle-status="c.template.lifecycleStatus"
    :can-edit-content-module-references="c.canEditContentModuleReferences"
    :coverage-refresh-token="c.coverageRefreshToken"
    :last-preview="c.lastPreview"
    :selected-preview-id="c.selectedPreviewId"
    :selected-test-data-set-id="c.selectedTestDataSetId"
    :show-draft-actions="c.showDraftActions"
    :show-testing-decision-actions="c.showTestingDecisionActions"
    :show-submit-for-approval="c.showSubmitForApproval"
    :show-approval-decision-actions="c.showApprovalDecisionActions"
    :show-publish-actions="c.showPublishActions"
    :show-test-generate="c.showTestGenerate"
    :show-stop-action="c.showStopAction"
    :show-restore-action="c.showRestoreAction"
    :show-deprecate-action="c.showDeprecateAction"
    :show-governance-section="c.showGovernanceSection"
    :publish-gate-items="c.publishGateItems"
    :loading-publish-gate="c.loadingPublishGate"
    :publish-bump-level="c.publishBumpLevel"
    :publish-version-conflict="c.publishVersionConflict"
    :publish-gate-ready="c.publishGateReady"
    :publish-bump-options="c.publishBumpOptions"
    :binding-gate-result="c.bindingGateResult"
    :publish-gate-load-error="c.publishGateLoadError"
    :submit-gate-items="c.submitGateItems"
    :loading-submit-gate="c.loadingSubmitGate"
    :submit-gate-ready="c.submitGateReady"
    :submit-gate-load-error="c.submitGateLoadError"
    :submitting="c.templatesStore.submitting"
    :generating-preview="c.generatingPreview"
    :generating-preview-id="c.generatingPreviewId"
    :batch-testing="c.batchTesting"
    :open-submit-for-test-dialog="c.submitForTestDialogOpen"
    @updated="c.loadTemplate"
    @update:selected-test-data-set-id="c.selectedTestDataSetId = $event"
    @update:selected-preview-id="c.handlePreviewSelected"
    @update:publish-bump-level="c.publishBumpLevel = $event"
    @update:open-submit-for-test-dialog="c.submitForTestDialogOpen = $event"
    @test-generate="c.handleTestGenerate"
    @test-generate-batch="c.handleBatchTestGenerate"
    @submit-for-test="c.handleSubmitForTest"
    @test-decision="c.handleTestDecision"
    @submit-for-approval="c.handleSubmitForApproval"
    @approval-decision="c.handleApprovalDecision"
    @publish="c.handlePublish"
    @governance-action="c.handleGovernanceAction"
    @retry-publish-gate="c.loadPublishGateData"
    @retry-submit-gate="c.loadSubmitGateData"
    @preview-refreshed="c.handlePreviewRefreshed"
  />

  <TemplateDetailLegacyWorkspace
    v-if="!c.isDevEditor"
    v-model:active-detail-tab="c.activeDetailTab"
    v-model:publish-bump-level="c.publishBumpLevel"
    v-model:credential-column-filters="c.credentialColumnFilters"
    v-model:credentials-current-page="c.credentialsCurrentPage"
    v-model:selected-contract-environment="c.selectedContractEnvironment"
    :template="c.template"
    :template-id="c.templateId"
    :detail-tabs="c.detailTabs"
    :format-date-time="c.formatDateTime"
    :show-lifecycle-section="c.showLifecycleSection"
    :show-governance-section="c.showGovernanceSection"
    :show-draft-actions="c.showDraftActions"
    :show-testing-decision-actions="c.showTestingDecisionActions"
    :show-submit-for-approval="c.showSubmitForApproval"
    :show-approval-decision-actions="c.showApprovalDecisionActions"
    :show-publish-actions="c.showPublishActions"
    :show-test-generate="c.showTestGenerate"
    :show-stop-action="c.showStopAction"
    :show-restore-action="c.showRestoreAction"
    :show-deprecate-action="c.showDeprecateAction"
    :show-authoring-section="c.showAuthoringSection"
    :can-edit-content-module-references="c.canEditContentModuleReferences"
    :show-policy-panel="c.showPolicyPanel"
    :coverage-refresh-token="c.coverageRefreshToken"
    :publish-gate-items="c.publishGateItems"
    :loading-publish-gate="c.loadingPublishGate"
    :publish-version-conflict="c.publishVersionConflict"
    :publish-gate-ready="c.publishGateReady"
    :publish-bump-options="c.publishBumpOptions"
    :binding-gate-result="c.bindingGateResult"
    :publish-gate-load-error="c.publishGateLoadError"
    :submit-gate-items="c.submitGateItems"
    :loading-submit-gate="c.loadingSubmitGate"
    :submit-gate-ready="c.submitGateReady"
    :submit-gate-load-error="c.submitGateLoadError"
    :submitting="c.templatesStore.submitting"
    :loading-policy="c.loadingPolicy"
    :api-policy="c.apiPolicy"
    :policy-load-failed="c.policyLoadFailed"
    :policy-load-error-key="c.policyLoadErrorKey"
    :paginated-credentials="c.paginatedCredentials"
    :credential-status-filter-options="c.credentialStatusFilterOptions"
    :total-credential-rows="c.totalCredentialRows"
    :policy-submitting="c.policySubmitting"
    :sort-credentials-by-created-at="c.sortCredentialsByCreatedAt"
    @open-submit-for-test="c.lifecycleCommentDialogOpen = true"
    @test-decision="c.handleTestDecision"
    @submit-for-approval="c.handleSubmitForApproval"
    @approval-decision="c.handleApprovalDecision"
    @publish="c.handlePublish"
    @test-generate="c.handleTestGenerate()"
    @governance-action="c.handleGovernanceAction"
    @retry-publish-gate="c.loadPublishGateData"
    @retry-submit-gate="c.loadSubmitGateData"
    @updated="c.loadTemplate"
    @create-credential="c.handleCreateCredential"
    @rotate-credential="c.handleRotateCredential"
    @revoke-credential="c.handleRevokeCredential"
    @retry-policy-load="c.loadPolicyData"
  />

  <TemplateDetailDialogs
    v-model:metadata-edit-open="c.metadataEditOpen"
    v-model:publish-summary-open="c.publishSummaryOpen"
    v-model:submit-summary-open="c.submitSummaryOpen"
    v-model:decision-dialog-open="c.decisionDialogOpen"
    v-model:lifecycle-comment-dialog-open="c.lifecycleCommentDialogOpen"
    v-model:credential-secret-dialog-visible="c.credentialSecretDialogVisible"
    :template-name="c.template.name"
    :template-description="c.template.description ?? null"
    :template-id="c.templateId"
    :submitting="c.templatesStore.submitting"
    :publish-version="c.publishVersion"
    :publish-gate-items="c.publishGateItems"
    :publish-coverage-summary="c.publishCoverageSummary"
    :publish-change-diff-summary="c.publishChangeDiffSummary"
    :submit-gate-items="c.submitGateItems"
    :submit-coverage-summary="c.submitCoverageSummary"
    :submit-change-diff-summary="c.submitChangeDiffSummary"
    :preview-comparison="c.lastPreview?.previewComparison ?? null"
    :decision-dialog-mode="c.decisionDialogMode"
    :lifecycle-comment="c.lifecycleComment"
    :credential-secret-external-id="c.credentialSecretExternalId"
    :displayed-credential-secret="c.displayedCredentialSecret"
    :credential-secret-value="c.credentialSecretValue"
    @metadata-submit="c.handleMetadataUpdate"
    @confirm-publish="c.confirmPublishFromSummary"
    @confirm-submit="c.confirmSubmitFromSummary"
    @submit-decision="c.submitLifecycleDecision"
    @submit-for-test="c.handleSubmitForTest"
  />
</template>
