/** Mirrors `DemoPublishRegistry.allPublishExternalIds()` / `Get-DemoPublishExternalIds`. */
export const DEMO_PUBLISH_EXTERNAL_IDS = [
  'CORP-FOL-OFFER',
  'DEMO-FULL-FLOW-LETTER',
  'DEMO-RETAIL-ACCOUNT-OPEN',
  'DEMO-RETAIL-ACCOUNT-BALANCE',
  'DEMO-MORTGAGE-APPROVAL',
  'DEMO-CREDIT-LIMIT-CONFIRM',
  'DEMO-TRADE-LC-NOTICE',
  'DEMO-TRADE-GUARANTEE-NOTICE',
  'DEMO-RATE-CHANGE-NOTICE',
  'DEMO-OVERDUE-COLLECTION',
  'DEMO-ANNUAL-REVIEW',
  'DEMO-FACILITY-RENEWAL',
  'DEMO-WEALTH-STATEMENT',
] as const

export type DemoPublishExternalId = (typeof DEMO_PUBLISH_EXTERNAL_IDS)[number]

/**
 * Per-template DOCX size floors (BDD-DEMO-TYP-012 anti-scaffold guard).
 * Calibrated from Docker runtime probe 2026-07-08 with ~10–15% headroom below observed sizes.
 */
export const DEMO_RUNTIME_MIN_DOCX_BYTES: Record<DemoPublishExternalId, number> = {
  'CORP-FOL-OFFER': 20_480,
  'DEMO-FULL-FLOW-LETTER': 2_560,
  'DEMO-RETAIL-ACCOUNT-OPEN': 4_096,
  'DEMO-RETAIL-ACCOUNT-BALANCE': 4_096,
  'DEMO-MORTGAGE-APPROVAL': 5_120,
  'DEMO-CREDIT-LIMIT-CONFIRM': 7_680,
  'DEMO-TRADE-LC-NOTICE': 5_120,
  'DEMO-TRADE-GUARANTEE-NOTICE': 5_120,
  'DEMO-RATE-CHANGE-NOTICE': 4_096,
  'DEMO-OVERDUE-COLLECTION': 4_096,
  'DEMO-ANNUAL-REVIEW': 5_120,
  'DEMO-FACILITY-RENEWAL': 4_608,
  'DEMO-WEALTH-STATEMENT': 5_120,
}
